# Generated by Django 2.0 on 2018-01-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180124_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('wname', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default='2017-12-11'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Publish', verbose_name='出版社'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ManyToManyField(to='app01.Writer', verbose_name='作者'),
        ),
    ]
